# Generated by Django 5.0.7 on 2025-02-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(choices=[('fire', '🔥'), ('like', '👍'), ('poop', '💩'), ('100', '💯 100%'), ('heart', '❤️ Сердечко')], max_length=10),
        ),
    ]
