# Generated by Django 5.0.7 on 2024-08-15 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_region_realestate_regi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='regi',
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='districts', to='real_estate.region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realestate',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_estates', to='real_estate.city'),
            preserve_default=False,
        ),
    ]
