# Generated by Django 5.0.7 on 2024-08-15 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0005_remove_realestate_re_realestate_street'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='streets', to='real_estate.region'),
            preserve_default=False,
        ),
    ]
