# Generated by Django 5.0.7 on 2025-02-01 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Описание услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('for_customer', models.TextField(help_text='Каждый пункт с новой строки', verbose_name='Для клиента')),
                ('benefit', models.TextField(verbose_name='Преимущества')),
                ('features', models.TextField(help_text='Каждый пункт с новой строки', verbose_name='Особенности')),
                ('duration', models.CharField(max_length=255, verbose_name='Длительность')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='ClientRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(max_length=255, verbose_name='Telegram')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultation.servicemodel', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Запрос от клиента',
                'verbose_name_plural': 'Запросы от клиента',
                'db_table': 'client_requests',
            },
        ),
    ]
