FROM python:3.12.4

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /api

COPY ./requirements.txt /api/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /api/requirements.txt

# Copy project
COPY . /api/

# Expose port
EXPOSE 8000

# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
