# Generated by Django 5.0.7 on 2024-12-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Категория задания',
                'verbose_name_plural': 'Категории заданий',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(max_length=30, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Приоритет',
                'verbose_name_plural': 'Приоритеты',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=100)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=30, null=True, verbose_name='Категория')),
                ('description', models.CharField(max_length=2500, verbose_name='Описание')),
                ('remark', models.CharField(blank=True, default='', max_length=2500, verbose_name='Примечания')),
                ('date_create', models.DateTimeField(verbose_name='Дата создания')),
                ('date_to_do', models.DateTimeField(verbose_name='Дата исполнения')),
                ('priority', models.CharField(max_length=30, verbose_name='Приоритет')),
                ('status', models.BooleanField(default=False, verbose_name='Статус исполнения')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=100)),
                ('day_date', models.DateField(verbose_name='День')),
                ('tasks', models.ManyToManyField(blank=True, related_name='day_tasks', to='models.task', verbose_name='задания')),
            ],
            options={
                'verbose_name': 'Дневной план',
                'verbose_name_plural': 'Дневные планы',
            },
        ),
    ]
