# Generated by Django 5.0.7 on 2024-12-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_categorycost_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='admin', max_length=100, verbose_name='Пользователь')),
                ('day_date', models.DateField(verbose_name='День')),
                ('costs', models.ManyToManyField(blank=True, related_name='day_costs', to='models.cost', verbose_name='Расходы')),
            ],
            options={
                'verbose_name': 'Дневной расход',
                'verbose_name_plural': 'Дневные расходы',
            },
        ),
    ]
