# Generated by Django 5.0.7 on 2024-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stack',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
