# Generated by Django 5.0.7 on 2024-08-15 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='city',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='street',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_estates', to='models.district'),
        ),
    ]
