# Generated by Django 5.0.7 on 2024-08-15 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_reg_realestate_r'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='r',
        ),
        migrations.AddField(
            model_name='realestate',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='real_estates', to='models.city'),
        ),
    ]
