# Generated by Django 5.0.7 on 2024-08-26 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_remove_realestate_r_realestate_street_delete_reg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchRequestFlat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('square', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('street', models.CharField(max_length=500)),
                ('floor', models.CharField(max_length=100)),
                ('number_of_storeys', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
