# Generated by Django 5.0.7 on 2024-08-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_rename_city_searchrequestflat_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(default=1),
        ),
    ]
