# Generated by Django 5.0.7 on 2024-08-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_alter_searchrequestflat_author_searchrequesthouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(),
        ),
    ]
