# Generated by Django 5.0.7 on 2024-08-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_searchrequestflat_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(default={'cities': []}),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='districts',
            field=models.JSONField(default={'districts': []}),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='streets',
            field=models.JSONField(default={'streets': []}),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='type',
            field=models.JSONField(default={'types': []}),
        ),
    ]
