# Generated by Django 5.0.7 on 2024-08-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_alter_searchrequestflat_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(default={'cities': []}, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='districts',
            field=models.JSONField(default={'districts': []}, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='streets',
            field=models.JSONField(default={'streets': []}, null=True),
        ),
    ]
