# Generated by Django 5.0.7 on 2024-08-30 09:02

import estate.models.search_requests
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_alter_searchrequestflat_streets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(default=estate.models.search_requests.SearchRequestFlat.get_default_cities, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='districts',
            field=models.JSONField(default=estate.models.search_requests.SearchRequestFlat.get_default_districts, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='streets',
            field=models.JSONField(default=estate.models.search_requests.SearchRequestFlat.get_default_streets, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='type',
            field=models.JSONField(default=estate.models.search_requests.SearchRequestFlat.get_default_types, null=True),
        ),
    ]
