# Generated by Django 5.0.7 on 2024-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_alter_searchrequestflat_cities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
