# Generated by Django 5.0.7 on 2024-08-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_alter_searchrequestflat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
