# Generated by Django 5.0.7 on 2024-08-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_alter_searchrequestflat_districts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchrequestflat',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='searchrequestflat',
            name='districts',
        ),
        migrations.RemoveField(
            model_name='searchrequestflat',
            name='streets',
        ),
    ]
