# Generated by Django 5.0.7 on 2024-08-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0024_remove_searchrequestflat_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchrequestflat',
            name='cities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrequestflat',
            name='districts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='searchrequestflat',
            name='streets',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
