# Generated by Django 5.0.7 on 2024-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_searchrequestflat_cities_searchrequestflat_districts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='square',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
