# Generated by Django 5.0.7 on 2024-08-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_alter_searchrequestflat_square'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchrequestflat',
            name='floor',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='number_of_storeys',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequestflat',
            name='rooms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='area',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='cities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='districts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='price',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='rooms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='square',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='streets',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchrequesthouse',
            name='type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
