# Generated by Django 5.0.7 on 2024-09-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кварира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'ordering': ['-created_at'], 'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Выводить на экран?'),
        ),
    ]
