# Generated by Django 5.0.7 on 2024-09-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
